#include "HiveSetup.h"
#include "LightSwitch.h"
#include "HiveStorage.h"

// Initialize global structures
SensorModule *sensorModuleArray[modulesCount];

// Settings storage file name (for SD card storage)
char StorageFileName[16] = "settings.txt"; // 15 characters long maximum

uint8_t SettingsOffset = 4;

// Init MAC adress of the Ethernet shield
// First 3 octets are OUI (Organizationally Unique Identifier)
// of GHEO Sa company. Other 3 octets will be randomly generated.
// orig. from http://nicegear.co.nz/blog/autogenerated-random-persistent-mac-address-for-arduino-ethernet/
byte hivemac[6] = { 0x90, 0xA2, 0xDA, 0x00, 0x00, 0x00 };

void initModules(AppContext *context, boolean loadSettings) {
  int lastStoragePointer = SettingsOffset;
  
  // If we're using SD card, there's no need to have on offset for system settings
  // which go to the EEPROM instead
  if (StorageType == SDStorage) {
  	lastStoragePointer = 0;
  }

  // Create objects for all sensor modules and init each one
  sensorModuleArray[0] = new LightSwitch(context, hallZone, 1, lastStoragePointer, loadSettings, 8, 4);
 
  lastStoragePointer += sensorModuleArray[0]->getStorageSize();
  
  // DEBUG
  Serial.println(F("Set up modules array"));
}